# Generated by Django 4.1 on 2022-12-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=25)),
                ('fecha_inscripcion', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora_inscripcion', models.TimeField()),
                ('estado', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
    ]
