# Generated by Django 4.1 on 2022-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], default=1, max_length=50),
        ),
    ]
