# Generated by Django 4.1 on 2022-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas_APP', '0002_alter_reservas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.CharField(max_length=50),
        ),
    ]
